name: Docker Image CI

on:
  push:
    branches: [ "buildpipe" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code
      uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
      
    - name: Build Application
      run: mvn -Pjar clean package
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iwa-java:latest
